version: "3.5"

services:

  phpmyadmin:
    container_name: ${M2C_CFG_DOMAIN_NAME}__phpmyadmin
    hostname: ${M2C_CFG_DOMAIN_NAME}__phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin-${M2C_PROJECT_NAME}.tls=true
      - traefik.http.routers.phpmyadmin-${M2C_PROJECT_NAME}.entryPoints=https
      - traefik.http.routers.phpmyadmin-${M2C_PROJECT_NAME}.rule=Host(`pma.${M2C_CFG_DOMAIN_NAME}`)
      - traefik.http.services.phpmyadmin-${M2C_PROJECT_NAME}.loadbalancer.server.port=80
    environment:
      - MYSQL_ROOT_PASSWORD=${M2C_CFG_MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_USER=${M2C_CFG_MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${M2C_CFG_MYSQL_PASSWORD:-magento}
      - PMA_HOST=${M2C_CFG_DOMAIN_NAME}__db
      - PMA_USER=${M2C_CFG_MYSQL_USER:-magento}
      - PMA_PASSWORD=${M2C_CFG_MYSQL_PASSWORD:-magento}
    networks:
      - m2c
      - default