version: "3.5"

services:

  phpmyadmin:
    container_name: ${M2C_CFG_DOMAIN_NAME}__phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:pma.${M2C_CFG_DOMAIN_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${M2C_CFG_MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_USER=${M2C_CFG_MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${M2C_CFG_MYSQL_PASSWORD:-magento}
      - PMA_HOST=${M2C_CFG_DOMAIN_NAME}__db
      - PMA_USER=${M2C_CFG_MYSQL_USER:-magento}
      - PMA_PASSWORD=${M2C_CFG_MYSQL_PASSWORD:-magento}
    networks:
      default:
        aliases:
          - pma.${M2C_CFG_DOMAIN_NAME}
      m2c:
        aliases:
          - pma.${M2C_CFG_DOMAIN_NAME}