version: "3.5"

services:

  rabbitmq:
    container_name: ${M2C_CFG_DOMAIN_NAME}__rabbitmq
    hostname: ${M2C_CFG_DOMAIN_NAME}__rabbitmq
    image: rabbitmq:${M2C_CFG_RABBITMQ:-3.7.15}-management-alpine
    labels:
      - traefik.enable=true
      - traefik.port=15672
      - traefik.frontend.rule=Host:rabbitmq.${M2C_CFG_DOMAIN_NAME}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - m2c
      - default

volumes:
  rabbitmq_data: