cluster.name: "docker-cluster"
node.name: "m2c-node"
network.host: 0.0.0.0
discovery.type: single-node

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.flood_stage: 200mb
cluster.routing.allocation.disk.watermark.low: 500mb
cluster.routing.allocation.disk.watermark.high: 300mb